[pipeline]
journals = ["American Chemical Society", "Science", "Mind", "The Lancet", "Cell", "Psychological Review"]
integrated_db_loc = "~/data/abstracts_integrated"
features_db_loc = "~/data/abstracts_integrated/"
start_year = 2023
end_year = 2022

[pipeline.log]
file = "ERROR"
console = "INFO"

[pipeline.names]
pipeline = "pipeline"
scrape = "scrape"
integration = "integration"
preprocess = "preprocess"
feature_extraction = "feature_extraction"

[scrape]
polite_email = "felix.noble@live.co.uk"
OPENALEX_BASE_URL = "https://api.openalex.org"
CROSSREF_BASE_URL = "https://api.crossref.org"
S2_BASE_URL = "https://api.semanticscholar.org/graph/v1"
S2_API_KEY = "424242"
output_dir = "~/data/abstracts/"
buffer_size = 100
max_retry = 3
polite_wait = 1.0
fail_wait = 10.0
rate_limit_wait = 60.0
timeout_wait = 5.0

start_year = 2023
end_year = 2022

S2_queries = ['paperId', 'externalIds', 'url', 'title', 'abstract', 'publicationDate', 'journal','isOpenAccess', 'openAccessPdf', 'citationCount', 'referenceCount', 'citations.paperId', 'citations.externalIds']

OpenAlex_queries = ["publication_date", "id", "doi", "type", "open_access", "source", "cited_by_count", 
                                          "cited_by_percentile_year_OpenAlex", "citation_normalized_percentile_OpenAlex", 
                                          "referenced_works", "title", "abstract_inverted_index", "topics"]
[scrape.log]
console = "INFO"
file = "ERROR"

[integration]
input_dir = "Placeholder Path value (overwrite this in script call)"
output_dir = ""
journal = "test"

[integration.log]
console = "INFO"
file = "ERROR"

[preprocess]
input_dir = "data/raw/American Chemical Society"
output_dir = "data/cleaned"
problem_chars = [")", "(", "[", "]", "}", "{"]
data_cols = ["year", "publicationDate", "doi", "abstract", "citationCount"]
cols_to_clean = ["abstract"]
chunk_size = 500
buffer_size = 600

[preprocess.log]
file = "ERROR"
console = "INFO"

[feature_extraction]
HuggingFace_model_name = "all-MiniLM-L12-v2"
journal = "test"

[feature_extraction.log]
console = "INFO"
file = "ERROR"

[staging]
database_loc = "E:/data/temp"

[staging.log]
console = "DEBUG"
file = "ERROR"
